# Nikita Tejwani
### HUDK 4050: Core Methods in Educational Data Mining
### Fall 2021

##### *Assignment 2: Individual Coding Assignment (ICE) 2*

In [3]:
#Import necessary packages

import numpy as np
import pandas as pd

##### DATA MANIPULATION IN ARRAY

In [15]:
np.random.seed(123)

arr_1 = np.random.randint(0, 100, size = 10)
arr_2 = np.random.randint(10, size = (3, 4))

print("Sample 1-dimensional array:\n", arr_1)

print("Sample 2-dimensional array:\n", arr_2)

print("\n\n")

print("First element in a 1-d array: arr_1[0] = ", arr_1[0])

print("First element in the second row in a 2-d array: arr_2[1, 0] = ", arr_2[1, 0])

print("Second, fourth, and sixth element in a 1-d array: arr_1[1:7:2] = ", arr_1[1:7:2]) #syntax = [start:end:countby]

Sample 1-dimensional array:
 [66 92 98 17 83 57 86 97 96 47]
Sample 2-dimensional array:
 [[9 0 0 9]
 [3 4 0 0]
 [4 1 7 3]]



First element in a 1-d array: arr_1[0] =  66
First element in the second row in a 2-d array: arr_2[1, 0] =  3
Second, fourth, and sixth element in a 1-d array: arr_1[1:7:2] =  [92 17 57]


##### DATA INDEXING IN SERIES

In [34]:
s1 = pd.Series([4, 5, 6, 7], index = ['w', 'x', 'y', 'z'])

print("First element in a series: s1['x'] = ", s1['x'])

print("First two elements in a series: s1['w':'y'] = \n", s1['w':'x'])

print("\nThe loc attribute indexes elements starting with 1, but iloc attribute indexes elements starting with 0.")

s1 = s1.reset_index().drop('index', axis = 1)

print("\ns1.loc[1] = ", s1.loc[1], "\n\ns1.iloc[1] = ", s1.iloc[1])

First element in a series: s1['x'] =  5
First two elements in a series: s1['w':'y'] = 
 w    4
x    5
dtype: int64

The loc attribute indexes elements starting with 1, but iloc attribute indexes elements starting with 0.

s1.loc[1] =  0    5
Name: 1, dtype: int64 

s1.iloc[1] =  0    5
Name: 1, dtype: int64


##### DATA INDEXING IN DATAFRAME

In [51]:
df = pd.read_csv("ICE1_Data.csv")

#Categorical variables are not ideal for data analysis.  So, it can be converted to a set of binary variables
#The binary variables consist of the set of values of the original categorical variables

df1 = pd.get_dummies(df['Quality_Review_Score'])
df.drop('Quality_Review_Score', axis = 1, inplace = True)
df = df.join(df1)

#View the first row of the dataframe 
df.loc[0]

#View the first two rows of the dataframe with only DBN, progress report, and student progress scores
df.iloc[:2, :3]

DBN Progress_Rpt_10-11 Student_Progress_10-11
0  01M292                  C                      C
1  01M448                  C                      B

##### DATA MASKING

In [60]:
#Locate all schools with a graduation rate above 95%
mask = df['graduation 2010-11'] > 0.95
df[mask]

#Locate all schools with a graduation rate above 95% and a school progress rating below A
mask = (df['graduation 2010-11'] > 0.95) & (df['Progress_Rpt_10-11'] != 'A')
df[mask]

DBN Progress_Rpt_10-11 Student_Progress_10-11  graduation 2010-11  \
5    01M696                  B                      C               0.976   
44   02M519                  B                      A               0.952   
259  17K590                  B                      C               0.975   
359  28Q680                  B                      B               0.990   
380  30Q580                  B                      B               1.000   
418  13K430                  B                      B               0.977   

     college enroll 2010-11  Developing  \
5                     0.957           0   
44                    0.750           0   
259                   0.684           0   
359                   0.898           0   
380                   0.903           0   
418                   0.867           0   

     Outstanding (only an option in 2007-8)  Proficient  Underdeveloped  \
5                                         0           0               0   
44                                        0           0               0   
259                                       0           1               0   
359                                       0           1               0   
380                                       0           1               0   
418                                       0           1               0   

     Underdeveloped with Proficient Features (only an option in 2007-8, 2008-9 and 2009-10)  \
5                                                    0                                        
44                                                   0                                        
259                                                  0                                        
359                                                  0                                        
380                                                  0                                        
418                                                  0                                        

     Well Developed  
5                 1  
44                1  
259               0  
359               0  
380               0  
418               0

##### COMBINING DATASETS

In [ ]:
#The join function has already been applied to add dummy variables to represent the categorical variable of school quality

##### AGGREGATION, GROUPING, AND PIVOT TABLES

In [75]:
df.mean()

#Total number of schools with each school progress report score
df[['DBN', 'Progress_Rpt_10-11']].groupby('Progress_Rpt_10-11').count()

#Average graduation rate (by school) for each school progress report score
#THIS IS NOT A RATE PER STUDENT
df[['graduation 2010-11', 'Progress_Rpt_10-11']].groupby('Progress_Rpt_10-11').mean()

graduation 2010-11
Progress_Rpt_10-11                    
A                             0.835587
B                             0.732363
C                             0.658306
D                             0.586818
F                             0.537000

In [82]:
#Making a pivot table showing counts of schools across two dimensions
df.pivot_table('Well Developed', index='Student_Progress_10-11', columns='Progress_Rpt_10-11', aggfunc = np.sum)

Progress_Rpt_10-11         A     B    C    D    F
Student_Progress_10-11                           
A                       38.0   4.0  NaN  NaN  NaN
B                       13.0  12.0  0.0  NaN  NaN
C                        2.0   9.0  7.0  0.0  NaN
D                        NaN   1.0  3.0  0.0  NaN
F                        NaN   NaN  1.0  0.0  0.0